language: python
python:
  - 2.7
  - 3.4

before_install:
  - sudo apt-get install libgeoip-dev

env:
  - DJANGO_VERSION="django==1.6.6"
  - DJANGO_VERSION="django==1.7"

install:
  - pip install -q $DJANGO_VERSION
  - pip install geoip

script: python runtests.py